name: Linting

on: [push, pull_request]

jobs:
  prettier:
    name: Prettier Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/jod'

      - name: Install dependencies
        run: npm ci

      - name: Run Jest tests
        run: npm run lint:prettier:check

  eslint:
    name: ESLint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/jod'

      - name: Install dependencies
        run: npm ci

      - name: Run Jest tests
        run: npm run lint:eslint:check
